update=4/17/2017 10:02:13 PM
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=transistors
LibName4=conn
LibName5=linear
LibName6=regul
LibName7=74xx
LibName8=cmos4000
LibName9=adc-dac
LibName10=memory
LibName11=xilinx
LibName12=microcontrollers
LibName13=dsp
LibName14=microchip
LibName15=analog_switches
LibName16=motorola
LibName17=texas
LibName18=intel
LibName19=audio
LibName20=interface
LibName21=digital-audio
LibName22=philips
LibName23=display
LibName24=cypress
LibName25=siliconi
LibName26=opto
LibName27=atmel
LibName28=contrib
LibName29=valves
LibName30=Component_Library/Front Panel
LibName31=switches
LibName32=C:/Program Files/KiCad/share/kicad/library/74xgxx
LibName33=C:/Program Files/KiCad/share/kicad/library/74xx
LibName34=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName35=C:/Program Files/KiCad/share/kicad/library/actel
LibName36=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName37=C:/Program Files/KiCad/share/kicad/library/allegro
LibName38=C:/Program Files/KiCad/share/kicad/library/Altera
LibName39=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName40=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName41=C:/Program Files/KiCad/share/kicad/library/atmel
LibName42=C:/Program Files/KiCad/share/kicad/library/audio
LibName43=C:/Program Files/KiCad/share/kicad/library/battery_management
LibName44=C:/Program Files/KiCad/share/kicad/library/bbd
LibName45=C:/Program Files/KiCad/share/kicad/library/bosch
LibName46=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName47=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName48=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName49=C:/Program Files/KiCad/share/kicad/library/conn
LibName50=C:/Program Files/KiCad/share/kicad/library/contrib
LibName51=C:/Program Files/KiCad/share/kicad/library/cypress
LibName52=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName53=C:/Program Files/KiCad/share/kicad/library/device
LibName54=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName55=C:/Program Files/KiCad/share/kicad/library/diode
LibName56=C:/Program Files/KiCad/share/kicad/library/display
LibName57=C:/Program Files/KiCad/share/kicad/library/dsp
LibName58=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName59=C:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName60=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName61=C:/Program Files/KiCad/share/kicad/library/gennum
LibName62=C:/Program Files/KiCad/share/kicad/library/graphic
LibName63=C:/Program Files/KiCad/share/kicad/library/hc11
LibName64=C:/Program Files/KiCad/share/kicad/library/intel
LibName65=C:/Program Files/KiCad/share/kicad/library/interface
LibName66=C:/Program Files/KiCad/share/kicad/library/ir
LibName67=C:/Program Files/KiCad/share/kicad/library/Lattice
LibName68=C:/Program Files/KiCad/share/kicad/library/leds
LibName69=C:/Program Files/KiCad/share/kicad/library/linear
LibName70=C:/Program Files/KiCad/share/kicad/library/logo
LibName71=C:/Program Files/KiCad/share/kicad/library/maxim
LibName72=C:/Program Files/KiCad/share/kicad/library/mechanical
LibName73=C:/Program Files/KiCad/share/kicad/library/memory
LibName74=C:/Program Files/KiCad/share/kicad/library/microchip
LibName75=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName76=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName77=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName78=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName79=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName80=C:/Program Files/KiCad/share/kicad/library/microchip_pic24mcu
LibName81=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName82=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName83=C:/Program Files/KiCad/share/kicad/library/modules
LibName84=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName85=C:/Program Files/KiCad/share/kicad/library/motorola
LibName86=C:/Program Files/KiCad/share/kicad/library/motors
LibName87=C:/Program Files/KiCad/share/kicad/library/msp430
LibName88=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName89=C:/Program Files/KiCad/share/kicad/library/nxp
LibName90=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName91=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName92=C:/Program Files/KiCad/share/kicad/library/opto
LibName93=C:/Program Files/KiCad/share/kicad/library/Oscillators
LibName94=C:/Program Files/KiCad/share/kicad/library/philips
LibName95=C:/Program Files/KiCad/share/kicad/library/power
LibName96=C:/Program Files/KiCad/share/kicad/library/Power_Management
LibName97=C:/Program Files/KiCad/share/kicad/library/powerint
LibName98=C:/Program Files/KiCad/share/kicad/library/pspice
LibName99=C:/Program Files/KiCad/share/kicad/library/references
LibName100=C:/Program Files/KiCad/share/kicad/library/regul
LibName101=C:/Program Files/KiCad/share/kicad/library/relays
LibName102=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName103=C:/Program Files/KiCad/share/kicad/library/sensors
LibName104=C:/Program Files/KiCad/share/kicad/library/silabs
LibName105=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName106=C:/Program Files/KiCad/share/kicad/library/stm8
LibName107=C:/Program Files/KiCad/share/kicad/library/stm32
LibName108=C:/Program Files/KiCad/share/kicad/library/supertex
LibName109=C:/Program Files/KiCad/share/kicad/library/switches
LibName110=C:/Program Files/KiCad/share/kicad/library/texas
LibName111=C:/Program Files/KiCad/share/kicad/library/transf
LibName112=C:/Program Files/KiCad/share/kicad/library/transistors
LibName113=C:/Program Files/KiCad/share/kicad/library/triac_thyristor
LibName114=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName115=C:/Program Files/KiCad/share/kicad/library/valves
LibName116=C:/Program Files/KiCad/share/kicad/library/video
LibName117=C:/Program Files/KiCad/share/kicad/library/wiznet
LibName118=C:/Program Files/KiCad/share/kicad/library/Worldsemi
LibName119=C:/Program Files/KiCad/share/kicad/library/Xicor
LibName120=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName121=C:/Program Files/KiCad/share/kicad/library/zetex
LibName122=C:/Program Files/KiCad/share/kicad/library/Zilog
